import os
import numpy as np
import torch
from torch.utils.data import Dataset
import random

# ================= Constant definitions =================
base2code = {'A': 0, 'C': 1, 'G': 2, 'T': 3}
MIN_COV = 20  # Number of reads sampled per site
SIGNAL_LEN = 65  # Number of columns in the signal matrix (after padding)
KMER_LEN = 5  # Kmer length


# ===========================================

class SiteLevelDataset(Dataset):
    """
    Reads site-level data generated by aggregate_reads.py.
    Revised version: correctly reads the label (0 or 1) at the end of each line.
    """

    def __init__(self, filename, min_cov=MIN_COV, transform=None, is_predict=False):
        self._filename = os.path.abspath(filename)
        self.min_cov = min_cov
        self.transform = transform
        self.is_predict = is_predict
        self.offsets = []
        self.length = 0

        # 1. Build the index (offsets)
        if os.path.exists(self._filename):
            print(f"[Dataset] Indexing file: {self._filename} ...")
            with open(self._filename, "r") as f:
                offset = 0
                for line in f:
                    if line.strip():
                        self.offsets.append(offset)
                        self.length += 1
                    offset += len(line)
            print(f"[Dataset] Indexed {self.length} sites. (Min coverage target: {self.min_cov})")
        else:
            raise FileNotFoundError(f"File not found: {self._filename}")

    def __len__(self):
        return self.length

    def __getitem__(self, idx):
        offset = self.offsets[idx]
        with open(self._filename, "r") as f:
            f.seek(offset)
            line = f.readline()

        try:
            return self.parse_site_line(line)
        except Exception as e:
            # Print errors for debugging and skip malformed lines
            # print(f"[Warning] Error parsing line at index {idx}: {e}")
            return None

    def parse_site_line(self, line):
        # Preprocess: remove leading and trailing whitespace
        line = line.strip()
        if not line:
            return None

        parts = line.split("\t")

        # ================= [Core modification starts] Label parsing logic =================
        # Goal: identify the label (0 or 1) and reads_block

        label = 0  # Default value to avoid parsing failure

        # Case A: standard training data, with the label at the end
        # Check the last part of parts
        last_part = parts[-1].strip()

        # Logic: determine whether the last part is a pure number or a long string containing reads

        # 1. If the last part is directly '0' or '1' (tab-separated case)
        if last_part in ['0', '1']:
            label = int(last_part)
            # This means the reads are in the second-to-last column
            # Standard format: Chr, Pos, Kmer, Reads, Label (len=5)
            # It may also be: Chr, Pos, Kmer, Reads (prediction mode, without label)
            if len(parts) >= 5:
                reads_block = parts[3]
            else:
                # Exceptional case: assume there is no label column and fall back
                reads_block = parts[3]

                # 2. If the last part is very long (space-separated case: "read_str/read_str... 1")
        # This is caused by the previous Python script using `line + " 1"`
        else:
            # Try splitting the last block by spaces
            last_tokens = last_part.split(' ')
            if len(last_tokens) > 1 and last_tokens[-1] in ['0', '1']:
                label = int(last_tokens[-1])
                # Remove the trailing label; the remainder is the reads
                reads_block = last_part[:-2].strip()  # Remove " 1" or " 0"
            else:
                # There is truly no label (prediction mode)
                label = 0
                reads_block = last_part

        # ================= [Core modification ends] =================

        # Basic information
        chrom = parts[0]
        pos = parts[1]
        kmer_str = parts[2]

        sample_info = f"{chrom}\t{pos}\t{kmer_str}"

        # Parse Kmer encoding
        try:
            kmer_code = np.array([base2code[x] for x in kmer_str])
        except KeyError:
            return None

        current_kmer_len = len(kmer_code)

        # Split and sample reads
        # Note: reads_block may be an empty string
        if not reads_block:
            raw_reads = []
        else:
            raw_reads = reads_block.split("/")

        num_reads = len(raw_reads)

        # If there are no reads, directly return all zeros (to avoid crashing)
        if num_reads == 0:
            batch_features = [self._get_zero_feature(current_kmer_len) for _ in range(self.min_cov)]
            features_tensor = np.array(batch_features, dtype=np.float32)
            return sample_info, features_tensor, int(label), kmer_str

        # Sampling strategy
        if num_reads < self.min_cov:
            selected_indices = np.random.choice(num_reads, self.min_cov, replace=True)
        else:
            selected_indices = np.random.choice(num_reads, self.min_cov, replace=False)

        selected_reads = [raw_reads[i] for i in selected_indices]

        batch_features = []

        # Parse read strings one by one
        for read_str in selected_reads:
            tokens = read_str.strip().split(" ")

            # Length check
            if len(tokens) < 9:
                batch_features.append(self._get_zero_feature(current_kmer_len))
                continue

            try:
                base_means = np.array([float(x) for x in tokens[0].split("|")])
                base_stds = np.array([float(x) for x in tokens[1].split("|")])
                base_median = np.array([float(x) for x in tokens[2].split("|")])
                qual = np.array([int(x) for x in tokens[4].split("|")])

                mis = np.array([int(x) for x in tokens[-3].split("|")])
                ins = np.array([int(x) for x in tokens[-2].split("|")])
                dele = np.array([int(x) for x in tokens[-1].split("|")])

                # Signal processing
                signal_tokens = tokens[5: 5 + current_kmer_len]
                k_signals_raw = [[float(y) for y in blk.split("|")] for blk in signal_tokens]

                k_signals_processed = np.zeros((len(k_signals_raw), SIGNAL_LEN))

                for i, sig_arr in enumerate(k_signals_raw):
                    sig_len = len(sig_arr)
                    if sig_len == 0: continue
                    if sig_len < SIGNAL_LEN:
                        pad0s = SIGNAL_LEN - sig_len
                        padl = pad0s // 2
                        k_signals_processed[i, padl: padl + sig_len] = sig_arr
                    else:
                        start = (sig_len - SIGNAL_LEN) // 2
                        k_signals_processed[i, :] = sig_arr[start: start + SIGNAL_LEN]

                k_signals = k_signals_processed.transpose()

                # Concatenation
                read_feature = np.concatenate((
                    kmer_code.reshape(-1, current_kmer_len),
                    base_means.reshape(-1, current_kmer_len),
                    base_median.reshape(-1, current_kmer_len),
                    base_stds.reshape(-1, current_kmer_len),
                    qual.reshape(-1, current_kmer_len),
                    mis.reshape(-1, current_kmer_len),
                    ins.reshape(-1, current_kmer_len),
                    dele.reshape(-1, current_kmer_len),
                    k_signals
                ), axis=0)

                batch_features.append(read_feature)

            except Exception as e:
                batch_features.append(self._get_zero_feature(current_kmer_len))

        features_tensor = np.array(batch_features, dtype=np.float32)

        return sample_info, features_tensor, int(label), kmer_str

    def _get_zero_feature(self, k_len):
        return np.zeros((8 + SIGNAL_LEN, k_len), dtype=np.float32)